### PR TITLE
Lancaster Scoring

### LINKED ISSUE #69: Feature Request: Add 11-zone (Lancaster) Target to scoring systems
It would be good to add the Lancaster Archery target as a possible scoring system (X is 11, compound and full face), and the Lancaster Classic round (18m, 40cm).

See chapter 4 of the [Lancaster Classic Rules](https://www.lancasterarcheryclassic.com/rules).

e.g.
```python
import archeryutils as au

myLancastertarget = au.Target("Lancaster", 40, 80)
myLancasterpass = au.Pass(30, "Lancaster", 40, 80, indoor=True)
myLancasterClassicRound = au.Round("lancaster_classic", [myLancasterpass, myLancasterpass])

myLancastertarget_comp = au.Target("Lancaster_6_ring", 40, 80)
myLancasterpass_comp = au.Pass(30, "Lancaster_6_ring", 40, 80, indoor=True)
myLancasterClassicRound_comp = au.Round("lancaster_classic_compound", [myLancasterpass_comp, myLancasterpass_comp])
```

### PR DESCRIPTION
**Pull request by jatkinson1000**
Closes #69 

Adds 11-zone scoring system and tests.
Adds Lancaster and Lancaster-compound rounds to misc rounds.

Checklist:

- [X] Source code updated to address issue
- [X] Style and formatting applied
- [X] Tests written to cover changes
- [X] ~Docstrings included/updated in code~
- [X] ~Project documentation updated as necessary~

### CODE REVIEW

**Comment by jatkinson1000** [comment]
@TomHall2020 How does this look to you?
A good chance for me to actually use the details of your latest PR in development.

**Comment by TomHall2020** [comment]
> @TomHall2020 How does this look to you? A good chance for me to actually use the details of your latest PR in development.
Neat, its good to be able to test drive the changes so soon. Just a quick once over on the diff and seems straightforward enough, knowing the docs should auto generate, the tests are in place for the face_spec and the expected handicaps, so I think that should be all it needs.

Only thought I have is on the JSON Round definition, it looks like `misc.lancaster` and `misc.lancaster_compound` are identical? If so trying to work out what the use of the second one is.

**Comment by jatkinson1000** [comment]
@TomHall2020 Oooo, good spot, horray for code review, and booo for copying and pasting code!
Submitted an amendment.

I did wonder if the compound 5-ring round should be the "default" or whether it should be the full face.
Decided on the full face for consistency with the WA and AGB rounds, though I imagine most recurves opt to shoot spots.

**Comment by TomHall2020** [comment]
If I understand right, the design choice of the new system was to treat everything (at least in terms of classification thresholds) as full face equivalent for simplicity (everything over a certain score will become equivalent anyway), so it seems like a downstream issue for users to decide if they want to work with full or reduced faces?

Didn't spot the fact that it was 6 zone instead of 5 zone faces though so good catch there.

Having just explicitly thought about it, and for consistency with the definitions of eg the `wa18`, `wa18_compound` and `wa18_triple` rounds, I'd actually rename these to `lancaster` and `lancaster_triple`, because the difference between them is not actually compound scoring at all, its the number of spots and the missing rings, so users should select whatever is appropriate for them.

**Comment by jatkinson1000** [comment]
Good point, thanks!
Have corrected that.

**Review by TomHall2020 — APPROVED** [review]
Looks good now.

**Pull request merged**
